/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    colors: {
      "primary": "#00503a",
      "primary-container": "#006a4e",
      "primary-fixed": "#9ef4d0",
      "primary-fixed-dim": "#83d7b4",
      "on-primary": "#ffffff",
      "on-primary-fixed": "#002116",
      "on-primary-fixed-variant": "#00513b",
      "secondary": "#715c00",
      "secondary-container": "#ffd31a",
      "secondary-fixed": "#ffe17b",
      "secondary-fixed-dim": "#ecc300",
      "on-secondary": "#ffffff",
      "on-secondary-container": "#705b00",
      "on-secondary-fixed": "#231b00",
      "on-secondary-fixed-variant": "#554500",
      "tertiary": "#900014",
      "tertiary-container": "#bd001e",
      "tertiary-fixed": "#ffdad7",
      "tertiary-fixed-dim": "#ffb3ae",
      "on-tertiary": "#ffffff",
      "on-tertiary-container": "#ffcac6",
      "on-tertiary-fixed": "#410004",
      "on-tertiary-fixed-variant": "#930015",
      "background": "#f9f9fc",
      "surface": "#f9f9fc",
      "surface-bright": "#f9f9fc",
      "surface-dim": "#dadadc",
      "surface-variant": "#e2e2e5",
      "surface-container-lowest": "#ffffff",
      "surface-container-low": "#f3f3f6",
      "surface-container": "#eeeef0",
      "surface-container-high": "#e8e8ea",
      "surface-container-highest": "#e2e2e5",
      "surface-tint": "#046c50",
      "on-background": "#1a1c1e",
      "on-surface": "#1a1c1e",
      "on-surface-variant": "#3f4944",
      "inverse-surface": "#2f3133",
      "inverse-on-surface": "#f0f0f3",
      "inverse-primary": "#83d7b4",
      "outline": "#6f7a73",
      "outline-variant": "#bec9c2",
      "error": "#ba1a1a",
      "error-container": "#ffdad6",
      "on-error": "#ffffff",
      "on-error-container": "#93000a",
      "white": "#ffffff",
      "black": "#000000",
      "transparent": "transparent",
      "current": "currentColor",
    },
    fontFamily: {
      "body-sm": ["Inter", "sans-serif"],
      "body-md": ["Inter", "sans-serif"],
      "body-lg": ["Inter", "sans-serif"],
      "headline-sm": ["Inter", "sans-serif"],
      "headline-md": ["Inter", "sans-serif"],
      "headline-lg": ["Inter", "sans-serif"],
      "headline-lg-mobile": ["Inter", "sans-serif"],
      "headline-xl": ["Inter", "sans-serif"],
      "label-md": ["Inter", "sans-serif"],
      "label-lg": ["Inter", "sans-serif"],
      "sans": ["Inter", "sans-serif"],
    },
    fontSize: {
      "body-sm": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
      "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
      "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
      "headline-sm": ["20px", { "lineHeight": "28px", "fontWeight": "600" }],
      "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
      "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "700" }],
      "headline-lg-mobile": ["28px", { "lineHeight": "34px", "fontWeight": "700" }],
      "headline-xl": ["40px", { "lineHeight": "48px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
      "label-md": ["12px", { "lineHeight": "16px", "fontWeight": "500" }],
      "label-lg": ["14px", { "lineHeight": "20px", "letterSpacing": "0.01em", "fontWeight": "600" }],
      "xs": ["12px", { "lineHeight": "16px" }],
      "sm": ["14px", { "lineHeight": "20px" }],
      "base": ["16px", { "lineHeight": "24px" }],
      "lg": ["18px", { "lineHeight": "28px" }],
      "xl": ["20px", { "lineHeight": "28px" }],
      "2xl": ["24px", { "lineHeight": "32px" }],
      "3xl": ["30px", { "lineHeight": "36px" }],
      "4xl": ["36px", { "lineHeight": "40px" }],
    },
    spacing: {
      "0": "0px",
      "px": "1px",
      "0.5": "2px",
      "1": "4px",
      "1.5": "6px",
      "2": "8px",
      "2.5": "10px",
      "3": "12px",
      "3.5": "14px",
      "4": "16px",
      "5": "20px",
      "6": "24px",
      "7": "28px",
      "8": "32px",
      "9": "36px",
      "10": "40px",
      "11": "44px",
      "12": "48px",
      "14": "56px",
      "16": "64px",
      "20": "80px",
      "24": "96px",
      "28": "112px",
      "32": "128px",
      "36": "144px",
      "40": "160px",
      "44": "176px",
      "48": "192px",
      "52": "208px",
      "56": "224px",
      "60": "240px",
      "64": "256px",
      "72": "288px",
      "80": "320px",
      "96": "384px",
      "gutter": "16px",
      "stack-sm": "8px",
      "stack-md": "16px",
      "stack-lg": "24px",
      "unit": "8px",
      "container-padding-mobile": "16px",
      "container-padding-desktop": "40px",
    },
    borderRadius: {
      "none": "0",
      "sm": "0.125rem",
      "DEFAULT": "0.25rem",
      "md": "0.375rem",
      "lg": "0.5rem",
      "xl": "0.75rem",
      "2xl": "1rem",
      "3xl": "3rem",
      "full": "9999px",
    },
    extend: {
      screens: {
        "sm": "640px",
        "md": "768px",
        "lg": "1024px",
        "xl": "1280px",
        "2xl": "1536px",
      },
      boxShadow: {
        "card": "0 4px 12px rgba(0,0,0,0.04)",
        "nav": "0 -2px 10px rgba(0,0,0,0.05)",
      },
    },
  },
  plugins: [],
}
